### PR TITLE
added the 'create react app', directory named my-app

### PR DESCRIPTION
**Pull request by thevon1**
@jsdevel @bifodus

### CODE REVIEW

**Comment by jsdevel** [comment]
@thevon1 move all the files in `my-app` up one directory, then delete the `my-app` directory e.g. `mv my-app/* .`.  Then verify that there are no files in `my-app` e.g. `ls -al my-app`, then delete `my-app` e.g. `rm -rf my-app`

**Comment by jsdevel** [comment]
@thevon1 looks like `mv my-app/* .` didn't copy hidden files :(  Probably best to undo this commit locally `git reset --hard HEAD^`.  That'll undo the last commit.

**Comment by jsdevel** [comment]
:+1:

**Comment by bifodus** [comment]
:+1:

**Pull request merged**
